#' Generate normal data with exact empirical standard deviation
#'
#' Simulates normally distributed data and optionally rescales it so that
#' the empirical (sample) standard deviation equals the specified value.
#'
#' @param n Number of observations.
#' @param mean Mean of the distribution.
#' @param sd Target standard deviation.
#' @param empirical Logical. If TRUE, rescale the simulated data so the
#'   sample standard deviation equals \code{sd}.
#'
#' @return A numeric vector of length \code{n}.
#'
#' @details
#' If \code{sd = 0}, a vector of zeros is returned.
#' If \code{empirical = FALSE}, data are returned as generated by
#' \code{rnorm()} without rescaling.
#'
#' @export
exact_rnorm <- function(n, mean = 0, sd = 1, empirical = TRUE) {

  stopifnot(
    is.numeric(n), length(n) == 1, n >= 0,
    is.numeric(mean), length(mean) == 1,
    is.numeric(sd), length(sd) == 1, sd >= 0
  )

  if (sd == 0) {
    return(rep(mean, n))
  }

  data <- stats::rnorm(n, mean = mean, sd = sd)

  if (empirical) {
    s <- stats::sd(data)
    if (s > 0) {
      data <- mean + (data - mean) * (sd / s)
    }
  }

  data
}
